//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace Pools
{ 
    public sealed class CapsulePool : BasePool<Capsule>
    {
        protected override void DestroyAction(Capsule instance)
        {
            base.DestroyAction(instance);
            Debug.Log("Overriden Destroy Capsule Action!");
        }

        protected override void GetAction(Capsule instance)
        {
            base.GetAction(instance);
            Debug.Log("Overriden Get Capsule Action!");
        }

        protected override void ReturnAction(Capsule instance)
        {
            base.ReturnAction(instance);
            Debug.Log("Overriden Return Capsule Action!");
        }
    }
}
